USE Crecer

declare @Empresa int

SELECT @Empresa=Codigo FROM Empresa

DELETE FROM Permisos

	INSERT INTO Permisos VALUES (1,16)
	INSERT INTO Permisos VALUES (2,16)
	INSERT INTO Permisos VALUES (3,16)
	INSERT INTO Permisos VALUES (4,16)
	INSERT INTO Permisos VALUES (5,16)
	INSERT INTO Permisos VALUES (1,84)
	INSERT INTO Permisos VALUES (2,84)
	INSERT INTO Permisos VALUES (3,84)
	INSERT INTO Permisos VALUES (4,84)
	INSERT INTO Permisos VALUES (5,84)
	INSERT INTO Permisos VALUES (1,10)
	INSERT INTO Permisos VALUES (2,10)
	INSERT INTO Permisos VALUES (3,10)
	INSERT INTO Permisos VALUES (4,10)
	INSERT INTO Permisos VALUES (5,10)
	INSERT INTO Permisos VALUES (1,101)
	INSERT INTO Permisos VALUES (2,101)
	INSERT INTO Permisos VALUES (5,101)
	INSERT INTO Permisos VALUES (1,1)
	INSERT INTO Permisos VALUES (2,1)
	INSERT INTO Permisos VALUES (3,1)
	INSERT INTO Permisos VALUES (4,1)
	INSERT INTO Permisos VALUES (5,1)
	INSERT INTO Permisos VALUES (1,3)
	INSERT INTO Permisos VALUES (2,3)
	INSERT INTO Permisos VALUES (3,3)
	INSERT INTO Permisos VALUES (4,3)
	INSERT INTO Permisos VALUES (5,3)
	INSERT INTO Permisos VALUES (1,2)
	INSERT INTO Permisos VALUES (2,2)
	INSERT INTO Permisos VALUES (3,2)
	INSERT INTO Permisos VALUES (4,2)
	INSERT INTO Permisos VALUES (5,2)
	INSERT INTO Permisos VALUES (1,7)
	INSERT INTO Permisos VALUES (2,7)
	INSERT INTO Permisos VALUES (3,7)
	INSERT INTO Permisos VALUES (4,7)
	INSERT INTO Permisos VALUES (5,7)
	INSERT INTO Permisos VALUES (1,25)
	INSERT INTO Permisos VALUES (2,25)
	INSERT INTO Permisos VALUES (3,25)
	INSERT INTO Permisos VALUES (4,25)
	INSERT INTO Permisos VALUES (5,25)
	INSERT INTO Permisos VALUES (2,36)
	INSERT INTO Permisos VALUES (5,36)
	INSERT INTO Permisos VALUES (2,72)
	INSERT INTO Permisos VALUES (5,72)
	INSERT INTO Permisos VALUES (1,105)
	INSERT INTO Permisos VALUES (2,105)
	INSERT INTO Permisos VALUES (3,105)
	INSERT INTO Permisos VALUES (4,105)
	INSERT INTO Permisos VALUES (5,105)
	INSERT INTO Permisos VALUES (1,15)
	INSERT INTO Permisos VALUES (2,15)
	INSERT INTO Permisos VALUES (3,15)
	INSERT INTO Permisos VALUES (4,15)
	INSERT INTO Permisos VALUES (5,15)
	INSERT INTO Permisos VALUES (1,4)
	INSERT INTO Permisos VALUES (2,4)
	INSERT INTO Permisos VALUES (5,4)
	INSERT INTO Permisos VALUES (2,12)	
	INSERT INTO Permisos VALUES (1,11)
	INSERT INTO Permisos VALUES (2,11)
	INSERT INTO Permisos VALUES (5,11)
	INSERT INTO Permisos VALUES (1,116)
	INSERT INTO Permisos VALUES (2,116)
	INSERT INTO Permisos VALUES (3,116)
	INSERT INTO Permisos VALUES (4,116)
	INSERT INTO Permisos VALUES (5,116)
IF @Empresa=1
BEGIN
	INSERT INTO Permisos VALUES (1,23)
	INSERT INTO Permisos VALUES (2,23)
	INSERT INTO Permisos VALUES (5,23)
	INSERT INTO Permisos VALUES (1,13)
	INSERT INTO Permisos VALUES (2,13)
	INSERT INTO Permisos VALUES (5,13)
	INSERT INTO Permisos VALUES (1,140)
	INSERT INTO Permisos VALUES (2,140)
	INSERT INTO Permisos VALUES (5,140)
	INSERT INTO Permisos VALUES (2,5)
	INSERT INTO Permisos VALUES (4,5)
	INSERT INTO Permisos VALUES (2,6)
	INSERT INTO Permisos VALUES (4,6)
END
ELSE
BEGIN 
	SELECT 1
END






