USE Crecer

declare @Empresa int

SELECT @Empresa=Codigo FROM Empresa
	INSERT INTO Permisos VALUES (1,51)
	INSERT INTO Permisos VALUES (2,51)
	INSERT INTO Permisos VALUES (3,51)
	INSERT INTO Permisos VALUES (5,51)
	INSERT INTO Permisos VALUES (1,49)
	INSERT INTO Permisos VALUES (2,49)
	INSERT INTO Permisos VALUES (3,49)
	INSERT INTO Permisos VALUES (5,49)
	INSERT INTO Permisos VALUES (1,75)
	INSERT INTO Permisos VALUES (2,75)
	INSERT INTO Permisos VALUES (5,75)
	/*INSERT INTO Permisos VALUES (1,18)
	INSERT INTO Permisos VALUES (2,18)
	INSERT INTO Permisos VALUES (3,18)
	INSERT INTO Permisos VALUES (5,18)
	INSERT INTO Permisos VALUES (1,30)
	INSERT INTO Permisos VALUES (2,30)
	INSERT INTO Permisos VALUES (4,30)
	INSERT INTO Permisos VALUES (5,30)
	INSERT INTO Permisos VALUES (1,32)
	INSERT INTO Permisos VALUES (2,32)
	INSERT INTO Permisos VALUES (5,32)
	INSERT INTO Permisos VALUES (1,52)
	INSERT INTO Permisos VALUES (2,52)
	INSERT INTO Permisos VALUES (3,52)
	INSERT INTO Permisos VALUES (5,52)
	INSERT INTO Permisos VALUES (2,117)
	INSERT INTO Permisos VALUES (1,142)
	INSERT INTO Permisos VALUES (2,142)
	INSERT INTO Permisos VALUES (4,142)
	INSERT INTO Permisos VALUES (5,142)
	INSERT INTO Permisos VALUES (1,66)
	INSERT INTO Permisos VALUES (2,66)
	INSERT INTO Permisos VALUES (3,66)
	INSERT INTO Permisos VALUES (5,66)
	*/

IF @Empresa=1
BEGIN

	INSERT INTO Permisos VALUES (1,64)
	INSERT INTO Permisos VALUES (2,64)
	INSERT INTO Permisos VALUES (3,64)
	INSERT INTO Permisos VALUES (4,64)
	INSERT INTO Permisos VALUES (5,64)
	INSERT INTO Permisos VALUES (1,130)
	INSERT INTO Permisos VALUES (2,130)
	INSERT INTO Permisos VALUES (5,130)
	INSERT INTO Permisos VALUES (1,138)
	INSERT INTO Permisos VALUES (2,138)
	INSERT INTO Permisos VALUES (5,138)
	INSERT INTO Permisos VALUES (2,110)
	INSERT INTO Permisos VALUES (4,110)
	INSERT INTO Permisos VALUES (1,118)
	INSERT INTO Permisos VALUES (2,118)
	INSERT INTO Permisos VALUES (5,118)
	INSERT INTO Permisos VALUES (1,97)
	INSERT INTO Permisos VALUES (2,97)
	INSERT INTO Permisos VALUES (5,97)
	INSERT INTO Permisos VALUES (1,35)
	INSERT INTO Permisos VALUES (2,35)
	INSERT INTO Permisos VALUES (5,35)
	INSERT INTO Permisos VALUES (1,48)
	INSERT INTO Permisos VALUES (2,48)
	INSERT INTO Permisos VALUES (5,48)
	INSERT INTO Permisos VALUES (2,41)
	INSERT INTO Permisos VALUES (3,41)
	INSERT INTO Permisos VALUES (1,47)
	INSERT INTO Permisos VALUES (2,47)
	INSERT INTO Permisos VALUES (3,47)
	INSERT INTO Permisos VALUES (5,47)
	INSERT INTO Permisos VALUES (1,107)
	INSERT INTO Permisos VALUES (2,107)
	INSERT INTO Permisos VALUES (4,107)
	INSERT INTO Permisos VALUES (5,107)
	INSERT INTO Permisos VALUES (1,112)
	INSERT INTO Permisos VALUES (2,112)
	INSERT INTO Permisos VALUES (4,112)
	INSERT INTO Permisos VALUES (5,112)
	INSERT INTO Permisos VALUES (1,121)
	INSERT INTO Permisos VALUES (2,121)
	INSERT INTO Permisos VALUES (5,121)
	select 1
END
ELSE
BEGIN 
	INSERT INTO Permisos VALUES (3,75)
	INSERT INTO Permisos VALUES (1,90)
	INSERT INTO Permisos VALUES (2,90)
	INSERT INTO Permisos VALUES (3,90)
	INSERT INTO Permisos VALUES (5,90)
	INSERT INTO Permisos VALUES (1,76)
	INSERT INTO Permisos VALUES (2,76)
	INSERT INTO Permisos VALUES (3,76)
	INSERT INTO Permisos VALUES (5,76)

/*	
	INSERT INTO Permisos VALUES (1,77)
	INSERT INTO Permisos VALUES (2,77)
	INSERT INTO Permisos VALUES (3,77)
	INSERT INTO Permisos VALUES (5,77)
	INSERT INTO Permisos VALUES (1,44)
	INSERT INTO Permisos VALUES (2,44)
	INSERT INTO Permisos VALUES (3,44)
	INSERT INTO Permisos VALUES (5,44)
	INSERT INTO Permisos VALUES (1,117)
	INSERT INTO Permisos VALUES (3,117)
	INSERT INTO Permisos VALUES (5,117)
	*/
	
	select 1
END






